version: '3'

services:
  database:
    container_name: ${CONTAINER_DB_NAME}
    image: ${DB_IMAGE}:${DB_VERSION}
    restart: unless-stopped
    volumes:
      - ${DB_FILES}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    depends_on:
      - database
    container_name: ${CONTAINER_SITE_NAME}
    image: ${SITE_IMAGE}:${SITE_VERSION}
    restart: unless-stopped
    volumes:
      - ${SITE_FILES}:/var/www/html
      - ./conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST: ${CONTAINER_DB_NAME}:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-200k}

  wpcli:
    image: tatemz/wp-cli
    volumes:
      - ${SITE_FILES}:/var/www/html
    depends_on:
      - database
    entrypoint: wp

networks:
   default:
     external:
       name: ${NETWORK}
